In [9]:
%pip install transformers

Note: you may need to restart the kernel to use updated packages.


In [11]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
text = "BERT preprocessing is essential. BERT is a transformer model."
tokens = tokenizer(text)
print(tokens)

{'input_ids': [101, 14324, 17463, 3217, 9623, 7741, 2003, 6827, 1012, 14324, 2003, 1037, 10938, 2121, 2944, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [12]:

from transformers import BertForSequenceClassification, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

text = "This movie was amazing!"
inputs = tokenizer(text, return_tensors='pt')
outputs = model(**inputs)
predictions = torch.argmax(outputs.logits, dim=1)
print(predictions)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([1])


In [15]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch 

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
text = "I love programming!"
inputs = tokenizer(text, return_tensors= 'pt')
outputs = model(**inputs)
predictions = torch.argmax(outputs.logits, dim=1)
print(predictions)


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([0])


In [17]:
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs, output_attentions=True)

attention_weights = outputs.attentions
print(attention_weights)

(tensor([[[[1.1471e-01, 9.7200e-02, 6.8047e-02, 8.7411e-02, 8.1343e-02,
           5.5129e-01],
          [1.8979e-01, 1.3331e-01, 1.5305e-01, 2.5262e-01, 1.9085e-01,
           8.0375e-02],
          [2.4287e-01, 1.1925e-01, 7.7998e-02, 1.8781e-01, 2.0021e-01,
           1.7186e-01],
          [6.3746e-02, 2.2557e-01, 2.0664e-01, 1.2482e-01, 2.5456e-01,
           1.2466e-01],
          [8.7550e-02, 1.1058e-01, 1.2209e-01, 1.7846e-01, 1.7363e-01,
           3.2769e-01],
          [1.7658e-01, 1.3155e-01, 1.1872e-01, 8.4194e-02, 2.3247e-01,
           2.5649e-01]],

         [[9.5042e-01, 2.2245e-02, 4.5349e-03, 4.5630e-03, 9.8712e-03,
           8.3618e-03],
          [8.8099e-03, 2.2828e-02, 2.5003e-01, 3.4970e-01, 3.2616e-01,
           4.2472e-02],
          [2.8968e-02, 1.2533e-02, 1.6299e-01, 5.2567e-01, 1.1071e-01,
           1.5912e-01],
          [3.5496e-02, 1.8830e-02, 8.3386e-02, 5.2465e-01, 9.1730e-02,
           2.4591e-01],
          [2.4742e-02, 3.5216e-02, 4.3923e-01, 

In [ ]:
class CustomBertModel(BertForSequenceClassification):
    def __init__(self, config):
        super().__init__(config)
        self.custom_layer = torch.nn.Linear(config.hidden_size, config.hidden_size)

    def forward(self, input_ids, attention_mask=None, labels=None):
        outputs = super().forward(input_ids, attention_mask=attention_mask, labels=labels)
        sequence_output = outputs[0]
        custom_output = self.custom_layer(sequence_output)
        return custom_output
from transformers import BertTokenizer, BertForSequenceClassification
import torch
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = CustomBertModel.from_pretrained('bert-base-uncased')
text = "This is a custom BERT model."                       